### ISSUE TITLE
Release notes issue v105

### ISSUE THREAD

**Issue by ross-spencer** [digital-preservation/PRONOM_Research#10]
The release notes currently reference x-fmts for some of the recent entries. These should be fmt.

![image](https://user-images.githubusercontent.com/1880412/177544768-10a73017-96f2-48ca-8f4a-7b886947569b.png)

https://www.nationalarchives.gov.uk/aboutapps/pronom/release-notes.xml

**Comment by tnafrancesca** [comment]
Thank you for spotting this! Should now be solved on the website and I've added some data validation to the release notes so hopefully the cause (whitespaces in xml) will mean it won't happen again.
