### ISSUE TITLE
Consider issue templates for PRONOM entries

### ISSUE THREAD

**Issue by ross-spencer** [digital-preservation/PRONOM_Research#17]
Based on the information on the README an [issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) may make things easier for folks finding this repository. 

They can appear in the UI as follows when creating an issue:

![image](https://user-images.githubusercontent.com/1880412/202195010-1c703af3-8869-4214-b1f1-0b786e0bae5b.png)

They can be created fairly easily at the following URL (if I have typed it correctly): https://github.com/digital-preservation/PRONOM_Research/issues/templates/edit

I have proposed two here based verbatim on the README: https://github.com/ross-spencer/tmp/tree/main/.github/ISSUE_TEMPLATE 
   * https://raw.githubusercontent.com/ross-spencer/tmp/main/.github/ISSUE_TEMPLATE/pronom_modification.md
   * https://raw.githubusercontent.com/ross-spencer/tmp/main/.github/ISSUE_TEMPLATE/pronom_submission.md

There's a lot that can be done with them too, including checklists. Folks can also be prompted to share samples using appropriate disclaimer and noting that they ensure that the samples are zipped first before being attached to the ticket.

**Comment by tnafrancesca** [comment]
This is a great idea and just at the right time. We were considering that our current system was a little unwieldy and thinking about moving to issues. I think we will implement this idea in the next month or so and will make sure to credit you! Thank you so much for working on this!

**Comment by prettybits** [comment]
I also think this is a good idea, one minor stylistic remark: the template names would read better to me if they just used spaces, i.e. "PRONOM Modification" (or "PRONOM Request for Modification"?) and "PRONOM Submission" respectively, there is no need to be careful and preemptively use underscores instead here I believe. :)

**Comment by ross-spencer** [comment]
Completed via a number of commits: https://github.com/digital-preservation/PRONOM_Research/commits/main/.github/ISSUE_TEMPLATE
