### ISSUE TITLE
New PRONOM entry: HMM Packfile

### ISSUE THREAD

**Issue by ross-spencer** [digital-preservation/PRONOM_Research#18]
**Format name**
Use the official name where known. Please capitalise each word unless the format name is stylised in some alternative way, e.g. Apple iBook.

* HMM packfile

**Extensions** 
any extensions known to be associated with the format.

* PAK, which is usually, capitalized. 

**Description**
a concise, objective description of the file format.

The HMM Packfile is a generic game data format that packages files for distribution with digital games. HMM likely stands for "Haemimont-Smartcom" who published at least three products with HMM Packfile objects.

**Format type**
What type of format is it (see below)?

* Aggregate.

**Vendor**
 (if known) - which vendor created the format? Which vendor currently supports it?

* Possibly "Haemimont-Smartcom", however, this hasn't been proven yet. 

**File format identification signatures**
(for the brave!).

Suggested signature is: 

* `484d4d535953205061636b46696c650a1a000000000000000000000000000000` these represent 32 consistent bytes that will be found at the beginning of a HMM packfile. There isn't an EOF sequence. 

**Additional information**

I have documented the format here with links to places where you can find sample files: http://fileformats.archiveteam.org/wiki/HMM_Packfile 

If the format is accepted, then please credit with `Ross Spencer, Ravensburger AG` 🙏🙇

**Comment by tnafrancesca** [comment]
This file format is now in our DevTest environment and has been assigned a PUID (fmt/1876) so will be available in the next release. Before closing the issue I wanted to check that you are still happy being credited as Ross Spencer, Ravensburger AG

**Comment by ross-spencer** [comment]
> are still happy being credited as Ross Spencer, Ravensburger AG

Works for me, thanks Francesca!
