### ISSUE TITLE
Corrections to signatures based on DROID/PRONOM discrepancies

### ISSUE THREAD

**Issue by Dclipsham** [digital-preservation/PRONOM_Research#20]
As per findings by Richard Lehane (https://github.com/richardlehane/siegfried/discussions/233), a handful of PRONOM signature peculiarities are manifesting as discrepncies between PRONOM's declared signature behaviours, and the DROID signature file output, so here are the suggested corrections:

- fmt/41 Raw JPEG Stream, specifically signatureID 697, named 'Photoshop JPEG' - set the EOF sequence 'offset' value to '0' - its absence appears to cause the maximum offset to be ignored
- fmt/1155 Lightwright Show File 5 (signature name 'Lightwright 5') - set the EOF sequence  'offset' value to '0' - its absence appears to cause the maximum offset to be ignored
- fmt/1556 Lightwright Show File 6 (signature name 'Lightwright 6') - set the EOF sequence  'offset' value to '0' - its absence appears to cause the maximum offset to be ignored
- fmt/1796 Wireless Markup Language (WML) Document (signature name 'Wireless Markup Language (WML) Document') - for the EOF sequence there is currently a trailing {0-2}, while the EOF offset itself is set as offset 0, maximum offset 3. The signature file is effectively summing these values, resulting in an effective EOF offset range of 0-5. The signature description suggests the intent is 0-2. If the intent is really 0-2, then please drop the trailing {0-2} from the signature sequence and set offset 0, maximum offset 2. If the intent is 0-5, please drop the trailing {0-2} from the signature sequence and set offset 0, maximum offset 5. 
- fmt/385 Microsoft Windows Cursor - I'm still looking into and will come back to you shortly.

Many thanks,
David

**Comment by Dclipsham** [comment]
For fmt/385, the DROID signature file is (in my view correctly) ignoring the offset range (offset 18, maximum offset 1024) associated with the Variable sequence. It doesn't make sense to use offset ranges with Variable sequences because it leads to the question 'offset to what?' - If it's intended to be offset to the BOF sequence then it should be part of the BOF sequence. Variable sequences by definition can be found anywhere within a given file.

The signature is effectively seeking the CUR magic at BOF (which isn't hugely strong - 0x00 00 02 00), and then some other specific byte fragments as part of the header, and then following a wildcard, some bitmap data. The variable section is seeking a second  set of bitmap data (.cur files usually store multiple images, representing the cursor at different sizes and potentially colours), so as it stands the signature as given by the DROID signature file does identify accurately (I've got a test set of around 200 files).

So, my suggestion here is to remove the 'offset' and 'maximum offset' values from variable seqeunce of the PRONOM entry for fmt/385 Microsoft Windows Cursor (signatureID 570 - name 'Microsoft Windows Cursor'). This won't affect the output data in the DROID signature file, but will ensure that PRONOM and DROID data is aligned and logically consistent.

David

**Comment by tnafrancesca** [comment]
Hi David,


All these updates are now in our DevTest environment and you can test the latest DevTest signature on Friday if you wish :)

In terms of variables having min and max offsets there are a few examples of variables with min-offsets. This is usually where a BOF sequence is also found and the variable is then set to start at a specific point in the file. These do show correctly in the xml and are on our list to look at. I think the question is whether we allow variables to have min offsets or merge these sequences with a * in the middle or delete the min offsets completely. Whilst I completely agree with the max-offset having no logic in a variable, I do see some logic (though still undecided) with them having a min-offset. Something to be looked into at some point. As you said removing the min-offset would make things consistent in the last example but there are lots of other inconsistencies. I made the change to fmt/385 but it might be good to revisit this later alongside all the other examples. I'll start compiling a list.
