### ISSUE TITLE
v112 update to fmt/649 MPEG-1 Elementary Stream causing identification clashes

### ISSUE THREAD

**Issue by Dclipsham** [digital-preservation/PRONOM_Research#24]
before v112, the fmt/649 MPEG-1 ES signature was:
000001B3{8}000001B8
It is now:
000001B3{8-136}000001B8

This now causes clashes with fmt/640 MPEG-2 ES, which is:
000001B3{8-256}000001B5{6-256}000001B8

I'm not sure what the intent was for adjusting the MPEG-1 signature, but I think this change should warrant MPEG-2 ES having priority over MPEG-1 ES now?

**Comment by kathaurielle** [comment]
Thanks for letting us know David, a user had found some files in the wild which necessitated a broadening of the signature. I've added the priority.

**Comment by Dclipsham** [comment]
Sorry I need to reopen this - it's listed in the release notes for v114 but the relationship remains absent in the release itself

**Comment by kathaurielle** [comment]
Oh no... this must have been missed over during copying, because it is in devtest. Have added it to v.115 spreadsheet and highlighted it, so it's not missed next time. Sorry.

**Comment by tnafrancesca** [comment]
This should now be fixed in v.115/v.116
