### ISSUE TITLE
Suggest removal of fmt/1618 'SGML/XML Entity File' signature

### ISSUE THREAD

**Issue by Dclipsham** [digital-preservation/PRONOM_Research#29]
Currently the signature for fmt/1618 SGML/XML Entity File is looking for:
BOF, offset 0: `<!--`
EOF, offset 0: `-->` followed by a linefeed character 0x0A

These are just generic open/close comment tags as used by languages including SGML/XML/HTML and derivatives, and so the potential for clashes is high.

Additionally real-world .ent examples such as https://[reviews.freebsd.org/file/data/7vpbtwi7eabpuqp6zirk/PHID-FILE-73osya6krjvpkkoi5oyv/authors.ent](https://reviews.freebsd.org/file/data/7vpbtwi7eabpuqp6zirk/PHID-FILE-73osya6krjvpkkoi5oyv/authors.ent) and https://github.com/php/doc-base/blob/master/entities/global.ent and https://wiki.linuxfromscratch.org/blfs/browser/gnome.ent demonstrate that the comment blocks aren't necessarily used at the beginning and end of the .ent file as the signature currently relies on.

Unfortunately the construct these files do use throughout, `<!ENTITY`, is commonly used by DTD also: https://www.w3schools.com/xml/xml_dtd_entities.asp

fmt/1618 is the only PUID currently to use .ent as an extension.

I therefore recommend removing the signature to make this an extension-only entry. Keen to hear others' thoughts though...

David

**Comment by tnafrancesca** [comment]
This will be affective as of v.115
