### ISSUE TITLE
Proposal to add 'image/webp' MIME type to WebP image formats

### ISSUE THREAD

**Issue by leninoc** [digital-preservation/PRONOM_Research#30]
hi,
would it be possible to add "image/webp" mime type to following PUIDs please:
fmt/566
fmt/567
fmt/568
image/webp seems to be official mime type for this format https://www.iana.org/assignments/media-types/image/webp

thank you
Jan Hutař on behalf of Archives New Zealand

**Comment by tnafrancesca** [comment]
This sounds great, thank you for the suggestion. We will put it in v.115.
