### ISSUE TITLE
PechaMaker format (new)

### ISSUE THREAD

**Issue by eroux** [digital-preservation/PRONOM_Research#31]
**Format name**

PechaMaker file

**Version number**
NA

**PUID**
NA

**Extensions** 
`.pxp`

**MIME/Media Type**
NA

**Description**
Files produced by the PechaMaker tool

**Format type**
Word Processor

**Vendor**
PechaMaker, http://www.pechamaker.com/

**File format identification signatures**
I'm not sure how to get this data properly, but if I open the files in `vim`, they start with `.pxp`

Here are two examples: 

[pechamaker-examples.zip](https://github.com/digital-preservation/PRONOM_Research/files/12485084/pechamaker-examples.zip)

You can credit `Buddhist Digital Resource Center` for this entry.

**Comment by tnafrancesca** [comment]
Hello,

This has been added to the signature in our development environment which can be downloaded from GitHub if you wish to test it/ or use the signature early. So will be part of our next release. Thank you so much for the submission, I will close this issue when the release is live.
