### ISSUE TITLE
New InDesign Format versions

### ISSUE THREAD

**Issue by thorsted** [digital-preservation/PRONOM_Research#35]
A couple years ago I updated all the [InDesign formats](https://github.com/digital-preservation/PRONOM_Research/tree/main/Submissions/Adobe%20InDesign%20Updates). Two new releases have happened since then. I suggest the two new additions.

**CC 2023** 0606EDF5D81D46E5BD31EFE7FE74B71D444F43554D454E54(01|02){4}(12000000|00000012)
**CC 2024** 0606EDF5D81D46E5BD31EFE7FE74B71D444F43554D454E54(01|02){4}(13000000|00000013)

**Comment by tnafrancesca** [comment]
These updates are now in our devtest environment and the test signature has been uploaded to GitHub if you wish to test across your samples before the release. When v.115 has been released I will close the issue

**Comment by tnafrancesca** [comment]
These has been included in v.115/v.116 release to be announced shortly
