### ISSUE TITLE
TibetDoc format (new)

### ISSUE THREAD

**Issue by eroux** [digital-preservation/PRONOM_Research#36]
**Format name**

TibetDoc file

**Version number**
NA

**PUID**
NA

**Extensions** 
`.dct`

**MIME/Media Type**
NA

**Description**
Files produced by the TibetDoc tool

**Format type**
Word Processor

**Vendor**
Padma Karpo Translation Committee (PKTC), https://pktc.org/tibetan-software/tibetdoc-wordprocessor/#7

**File format identification signatures**
It starts with a distinctive sequence of bytes that should be easy to identify (see example)

[TibetDocExamples.zip](https://github.com/digital-preservation/PRONOM_Research/files/13209378/TibetDocExamples.zip)

You can credit `Buddhist Digital Resource Center` for this entry.

I've sent this on the online form, got a response that it would be considered for the next release end of September but I'm not sure what the status is, I thought it would be easier to track it here

**Comment by tnafrancesca** [comment]
Hi,
Thank you for posting this here. We were delayed on the release this September but this format will still be part of our next release which is due by the end of November. I will close this issue when v.115 is released. Thank you for all your patience.

**Comment by tnafrancesca** [comment]
This has been added to our v.116 release that will be announced shortly. Let us know if it works well
