### ISSUE TITLE
enhancement to signature for MIME email (.eml) files - fmt/950

### ISSUE THREAD

**Issue by leninoc** [digital-preservation/PRONOM_Research#37]
hi,
we just received a born digital transfer with 60 .eml files, 14 of them failed format identification in DROID 6.5.2 (sig112 and 114). I tried to figure out why, all the strings in the signature are there in those 14 failed eml files. Then I realised its the offset limit causing DROID to fail the identification via signature. 
For the "MIME-Version: 1.0" or 4D(494D45|696D65)2D(56|76)657273696F6E3A20312E30 the maximum offset value is 16384. All those 14 trouble files have the MIME-Version: 1.0 after 16384 offset. All of them have it between 16385 and 20000 offset. See below.
<img width="594" alt="image" src="https://github.com/digital-preservation/PRONOM_Research/assets/10123079/bb806481-9bc4-4393-aa8c-c11390fc7293">
When I edited the max offset in signature file to 20000 for MIME-Version: 1.0 and then used this sig in DROID all the problematic .eml files were correctly identified as fmt/950 via signature.
PROPOSAL- raise the max offset value from 16384 for the "MIME-Version: 1.0" (byte sequence 4D(494D45|696D65)2D(56|76)657273696F6E3A20312E30). 
Sorry I cannot share any of those problematic .eml files, sensitive content. 
Happy to help and answer any questions.
thank you
Jan

**Comment by tnafrancesca** [comment]
Dear Jan,

Thank you for this suggestion- I will be adding it to the next PRONOM release. Would you be able to let me know how you would wish to be credited in the release notes (if at all)?

**Comment by leninoc** [comment]
hi Francesca,
thats great news, looking forward to it. Regarding credit - just say Archives New Zealand, thank you!
Jan

Sent with [Proton Mail](https://proton.me/) secure email.
