### ISSUE TITLE
Update to x-fmt/436 CATIA Model file 4

### ISSUE THREAD

**Issue by themaskedtaquito** [digital-preservation/PRONOM_Research#41]
Format name: CATIA Model 4
PUID: x-fmt/436
Attribution: J. Paul Getty Trust

This signature can be broken down into 2 separate byte sequences. Currently, the offset between the two sequences is described as a fixed number of bytes, 2024. After analyzing files held in Getty's preservation system, I've observed that the offset can be extremely variable. I will share sample files via email.

Updated signature
BOF Offset: 80
Value: 4341544941202020*434154494120534F4C5554494F4E53205634{6}52454C4541534520

**Comment by kathaurielle** [comment]
Hello, Thanks for your email.  I've adjusted the sig, and all your files are now IDing. This change will go live in our v.118 release. Would you like to be credited as J. Paul Getty Trust? Best wishes, Kathryn.

**Comment by themaskedtaquito** [comment]
Hello, Thank you for the update! Yes I'd like to be credited as J. Paul Getty Trust.
