### ISSUE TITLE
New format signature variant for ZIP - X-fmt/263

### ISSUE THREAD

**Issue by Dclipsham** [digital-preservation/PRONOM_Research#42]
This is spawned from a discussion over on the Siegfried repo: https://github.com/richardlehane/siegfried/discussions/239

Please add a second variant signature to the existing ZIP Format entry (x-fmt/263):
Siganture Name: Zip Format - Empty Zip
Signature Description: BOF: 'PK', 0x0506 denoting the end of the central directory
Signature, BOF offset 0, maximum offset 0: 504B0506

Note, this should be strong enough as it is (4 byte mix of ASCII & binary with an exact position), but it could be strengthened if needed by using subsequent 0x0000 blocks as described on @marhop comment: https://github.com/richardlehane/siegfried/discussions/239#discussioncomment-8186526

An example is enclosed: [empty.zip](https://github.com/digital-preservation/PRONOM_Research/files/14008884/empty.zip)

This issue was initially raised by @JanVomlel

**Comment by tnafrancesca** [comment]
The new signature will be added to the latest release. Would it be possible to have a list of everyone who contributed (and how they would wish to be credited on the PRONOM website). I'll be putting the new test signature online at the end of the day for any testing you may wish to do.

**Comment by JanVomlel** [comment]
Thank you @tnafrancesca for the quick reaction.

This bug was found by the 
Institute of the History of Charles University and Archive of Charles University
https://udauk.cuni.cz/ARCHEN-1.html
