### ISSUE TITLE
enhancement to signature for geoTIFF fmt/155

### ISSUE THREAD

**Issue by leninoc** [digital-preservation/PRONOM_Research#43]
hi,
i would like to propose a change to signature for fmt/155 geoTIFF. We are receiving geoTIFF files from an government agency and some of the files are identified as fmt/353 normal TIFF, although they are geoTIFFs for sure. Looking into it I realised its the max offset from EOF which has a value of 4088 for AF870300, causing this. In all our geoTiffs AF870300 is beyond 4088 ofset, actually its at 4373 from EOF. 
When I raised the SubSeqMaxOffset value in InternalSignature 678 for EOFoffset to 5000 then DROID identifed our files correctly as fmt/155 (and not fmt/353).
You can download test files from here https://drive.proton.me/urls/K3HKR4R590#zorKi7tmRI2o (can be accessed for next 30 days)

thank you on behalf of Archives New Zealand

**Comment by tnafrancesca** [comment]
Hello,
I'm adding this to our next release. Thank you. I'll close the issue when it has been released but if you need it earlier I will upload the development signature to our GitHub today.

**Comment by leninoc** [comment]
thank you, no need to rush this one, we can totally wait for release, cheers
