### ISSUE TITLE
ETC Expression Show File

### ISSUE THREAD

**Issue by sbshep** [digital-preservation/PRONOM_Research#45]
**Format name**
ETC Expression Show File

**Version number**
n/a

**PUID**
n/a

**Extensions** 
.shw

**MIME/Media Type**
application/octet-stream

**Description**
Used by ETC’s Express or Expression console for stage lighting. The file would be stored on a floppy disk for use in the console. Expression-offline software (https://www.etcconnect.com/Products/Legacy/Console/Others/Express/Software.aspx) can convert from .shw to .asc (ASCII) text file and can import either file type. 

**Format type**
I'm not sure how to classify it. 

**Vendor**
ETC https://www.etcconnect.com/ 

**References**
Expression Off-Line QuickGuide Version 3.1 https://web.archive.org/web/20051126055839/http://www.etcconnect.com/docs_downloads/manuals/Expression_Off-Line_v3.1_Quick_Guide.pdf 
Expression Console Technical Support https://www.etcconnect.com/Products/Legacy/Console/Others/Expression/Support-Articles.aspx 
Express Console Technical Support https://www.etcconnect.com/Products/Legacy/Console/Others/Express/Software.aspx 
File Format Wiki entry http://fileformats.archiveteam.org/wiki/ETC_Show_File 

**File format identification signatures**
4554432045585020 from BOF (reads in ASCII as "ETC EXP")

Please credit "The Church of Jesus Christ of Latter-day Saints" for this signature.

Two samples and a test file signature XML below:
[ETC Expression Show File signature and samples.zip](https://github.com/digital-preservation/PRONOM_Research/files/14115616/ETC.Expression.Show.File.signature.and.samples.zip)

**Comment by tnafrancesca** [comment]
Thank you for your research, I've created an entry for this in the latest release which will hopefully go out in the next few weeks. I'll close the issue then

**Comment by tnafrancesca** [comment]
In latest v.118 release
