### ISSUE TITLE
typo in fmt/1911 MIME type (appliction/pdf - missing "a")

### ISSUE THREAD

**Issue by leninoc** [digital-preservation/PRONOM_Research#47]
hi,
there seems to be a typo in fmt/1911 MIME type, both in the sig file and PRONOM DB, appliction/pdf - missing "a". Spotted by @thorsted.
 
<img width="543" alt="image" src="https://github.com/digital-preservation/PRONOM_Research/assets/10123079/d1c15a85-294e-4ebc-b4a0-d388f9bdfddf">

Thank you,
Jan

**Comment by tnafrancesca** [comment]
Hello,

Thank you so much for raising the issue.

Just to clarify the suggestion is that the mime type should be application/pdfa? If so I was wondering if there was any documentation from the developers that the mime type for pdf/a is supposed to be application/pdfa?

**Comment by leninoc** [comment]
hi Francesca, there is missing "a" in the word "application", not pdf. Sorry that I haven't been more clear.
thank you
Jan

**Comment by tnafrancesca** [comment]
Oh of course, I see it now! Thank you for pointing this out, I'll put it in the next release due in a couple of weeks
