### ISSUE TITLE
Add entries for ICC profile format versions 2, 4 and 5

### ISSUE THREAD

**Issue by BertrandCaron** [digital-preservation/PRONOM_Research#50]
**Format name**
ICC Profile

**Version number**
version 2
version 4
version 5 - iccMAX

**Extensions** 
icc
icm

**MIME/Media Type**
Unofficial MIME type: application/vnd.iccprofile

**Description**
An ICC Profile is a set of data that describes how a peripheral renders colors.

**Vendor**
International Color Consortium
Specifications available at https://color.org/icc_specs2.xalter
Examples available at https://www.color.org/profiles2.xalter

**File format identification signatures**
Version 2: 02{27}61637370
Version 4: 04{27}61637370
Version 5 - iccMAX: 05{27}61637370

If the signature is not strong enough, maybe the 7 (version 2) to 11 (version 5) different values for the Profile / device class (offset 11 to 15) can be used?

**Comment by tnafrancesca** [comment]
Thank you for the submission. This looks great. How would you wish to be credited in the release notes (if at all). Normally this is by institutions but it can be by individual if that is your preference?

**Comment by BertrandCaron** [comment]
Both would be nice ;-) but if you have to choose, I'd prefer my institution to be credited (Bibliothèque nationale de France)!
