### ISSUE TITLE
Update to Extensible Metadata Platform Packet signature

### ISSUE THREAD

**Issue by amanda-tome** [digital-preservation/PRONOM_Research#55]
Hello, 

I am proposing an update to the Extensible Metadata Platform Packet format to include more flexibility in the signature. The changes account for the use of both single quotes (') and double quotes (").

Thanks.

**Format name**

Extensible Metadata Platform Packet

**PUID**
if it exists already and you're providing an enhanced description.
fmt/570

**Extensions** 
any extensions known to be associated with the format.

.xmp

**File format identification signatures**
3C3F787061636B657420626567696E3D(22|27)EFBBBF(22|27)2069643D(22|27)57354D304D7043656869487A7265537A4E54637A6B633964(22|27)3F3E0A3C783A786D706D65746120786D6C6E733A783D(22|27)61646F62653A6E733A6D6574612F(22|27)

**Comment by tnafrancesca** [comment]
Hi Amanda
This will be in the next release of PRONOM. I just wanted to check how you would wish to be credited in the PRONOM release notes (if at all). Normally this is done by institution but does not have to be.

**Comment by amanda-tome** [comment]
Hi Francesca,
Would it be possible to have the credit read Digital Research Alliance of Canada / Alliance de recherche numérique du Canada? It would need to include both the English and the French as we are a federal organization.

**Comment by amanda-tome** [comment]
@tnafrancesca Is it too late to change the credit? We had a request from the developers to include the name of the repository and I think the request is a good one as not all people that contribute and work on the Federated Research Data Repository (FRDR) are Alliance employees. The credit would be Digital Research Alliance of Canada - Federated Research Data Repository / Alliance de recherche numérique du Canada - Dépôt fédéré de données de recherche

**Comment by tnafrancesca** [comment]
Closing this as it is now in v.119- let me know if there are any problems
