### ISSUE TITLE
KryoFlux Raw

### ISSUE THREAD

**Issue by marynacher** [digital-preservation/PRONOM_Research#58]
Thank you for choosing to submit a new entry to PRONOM. For each submission, please include as much of the following information as possible. It's okay if you don't have everything, but please include what you can.

**Format name**
Use the official name where known. Please capitalise each word unless the format name is stylised in some alternative way, e.g. Apple iBook.

KryoFlux Stream file

**Version number**
(where relevant)

3.00s

**PUID**
if it exists already and you're providing an enhanced description.

**Extensions** 
any extensions known to be associated with the format.

raw

**MIME/Media Type**
the MIME or Media Type associated with the format. A brief description of what a MIME type is can be found here. This should be an official Media Type, either registered and listed via the IANA or listed in official format documentation produced by the vendor. The best way to search IANA is to find in page and search for key words of the format.

application/octet-stream

**Description**
a concise, objective description of the file format.

KryoFlux is a software-programmable FDC (Floppy Disk Controller) system that runs on small ARM7-based devices and connects to a host PC over a USB connector. It reads and writes flux transitions on floppy disks at a very fine resolution.
(borrowed from: https://www.nationalarchives.gov.uk/pronom/fmt/656)

**Format type**
What type of format is it (see below)?

**Vendor**
 (if known) - which vendor created the format? Which vendor currently supports it?

KryoFlux Products & Services Limited

**File format identification signatures**
(for the brave!). If you'd like to find out more about creating file format signatures please refer to our starter pack under resources.

Signature: B0F, offset min 0, max 60: 4B72796F466C7578204469736B53797374656D2C2076657273696F6E3D332E303073

More info: https://www.loc.gov/preservation/digital/formats/fdd/fdd000610.shtml

**Comment by Dclipsham** [comment]
Just a bit of additional info - I can't find an official media type so that can be left blank (application/octet-stream is just the default that the sigdev tool uses). As it's a disk image the format type is Aggregate. 

Minor tweak to the signature sequence as it's a precise offset, so offset=60, maximum offset=0 (the maximum offset is relative to the initial offset value, so in this case is 0 as the string we're looking for is exactly at offset 60)
Sig description is: BOF, offset 60, 'KryoFlux DiskSystem, version=3.00s'

David

**Comment by thorsted** [comment]
I can confirm this signature and note that the latest release of Kryoflux 3.5 still writes to "version=3.00". I do have some older Kyroflux raw files which state "KryoFlux DiskSystem, version=2.20s". So maybe a couple PUID's can be added for Version 2 and Version 3. 

Would it be better to stop at the first major version? The signature would be "KryoFlux DiskSystem, version=3" and "KryoFlux DiskSystem, version=2", to avoid missing point updates?
