### ISSUE TITLE
Axon Binary Format

### ISSUE THREAD

**Issue by amanda-tome** [digital-preservation/PRONOM_Research#61]
**Format name**
Use the official name where known. Please capitalise each word unless the format name is stylised in some alternative way, e.g. Apple iBook.

Axon Binary Format

**Version number**
(where relevant)

1

**PUID**
if it exists already and you're providing an enhanced description.
N/A

**Extensions** 
any extensions known to be associated with the format.

abf

**MIME/Media Type**
the MIME or Media Type associated with the format. A brief description of what a MIME type is can be found here. This should be an official Media Type, either registered and listed via the IANA or listed in official format documentation produced by the vendor. The best way to search IANA is to find in page and search for key words of the format.

I couldn't find one in IANA

**Description**
a concise, objective description of the file format.

The Axon Binary Format was created to store binary experimental data. It originated with the pCLAMP suite of programs in the late 1990s, and is also supported by AxoTape and AxoScope. The Axon binary format is encoded as a proprietary format, however it can be read and created by third-party developers. This file format is commonly used in the life sciences.

**Format type**
What type of format is it (see below)?

Dataset

**Vendor**
 (if known) - which vendor created the format? Which vendor currently supports it?

[Molecular Devices](https://www.moleculardevices.com/) currently supports the format.

**File format identification signatures**
(for the brave!). If you'd like to find out more about creating file format signatures please refer to our starter pack under resources.

BOF; Offset: 0; Magic Bytes: ABF 
41424620

Note that there is a space after ABF. According to the documentation the space denotes version 1 of the file format.

Sample files can be found in the following dataset: https://doi.org/10.20383/101.0204

**Comment by tnafrancesca** [comment]
Hello,
Can I just check how you wish to attributed for this in the release notes and on the database?

**Comment by amanda-tome** [comment]
@tnafrancesca Digital Research Alliance of Canada - Federated Research Data Repository / Alliance de recherche numérique du Canada - Dépôt fédéré de données de recherche
