### ISSUE TITLE
Binvox

### ISSUE THREAD

**Issue by amanda-tome** [digital-preservation/PRONOM_Research#62]
**Format name**
Use the official name where known. Please capitalise each word unless the format name is stylised in some alternative way, e.g. Apple iBook.

Binvox

**Version number**
(where relevant)

1

**PUID**
if it exists already and you're providing an enhanced description.

**Extensions** 
any extensions known to be associated with the format.

binvox

**MIME/Media Type**
the MIME or Media Type associated with the format. A brief description of what a MIME type is can be found here. This should be an official Media Type, either registered and listed via the IANA or listed in official format documentation produced by the vendor. The best way to search IANA is to find in page and search for key words of the format.

I couldn't find one in IANA or in the documentation.

**Description**
a concise, objective description of the file format.

Binvox files are the output of the voxelizer software Binvox and are the result of the rasterization of a 3D model into a binary 3D voxel grid. A .binvox file features a short header followed by binary data.

**Format type**
What type of format is it (see below)?

Model

**Vendor**
 (if known) - which vendor created the format? Which vendor currently supports it?

This format is linked to Patrick Min and Michael Kazhdan: https://www.patrickmin.com/binvox/binvox.html

**File format identification signatures**
(for the brave!). If you'd like to find out more about creating file format signatures please refer to our starter pack under resources.

BOF; Offset: 0; Magic Bytes: #binvox 1

2362696E766F7820310A

**Comment by tnafrancesca** [comment]
Can I just check the attribution for this one?
