### ISSUE TITLE
xdomea 3.0.0 (fmt/1813) - Update link to schema files

### ISSUE THREAD

**Issue by marhop** [digital-preservation/PRONOM_Research#63]
Hi,

the link to the schema files in the description of [fmt/1813](https://www.nationalarchives.gov.uk/PRONOM/fmt/1813), https://xdomea.de/schemata/300/ does not work anymore. The schema files are now here:

https://www.xrepository.de/api/xrepository/urn:xoev-de:xdomea:kosit:standard:xdomea_3.0.0:xmlschema

By the way, this new link corresponds nicely to the link to the specification in the Note section of the PRONOM entry:

https://www.xrepository.de/api/xrepository/urn:xoev-de:xdomea:kosit:standard:xdomea_3.0.0:dokument:Spezifikation_xdomea_3.0.0

Cheers,
Martin

**Comment by tnafrancesca** [comment]
Thank you, that will be out with the next release
