### ISSUE TITLE
Synchronized Multimedia Integration Language

### ISSUE THREAD

**Issue by thorsted** [digital-preservation/PRONOM_Research#67]
The signature for [fmt/205](https://www.nationalarchives.gov.uk/PRONOM/fmt/205) has a short variable byte sequence which needs to be expanded.

Currently looks for {20-86} bytes between XML declaration and the beginning of the <smil> tag. If XML has a DOCTYPE, then more bytes are needed.

Recommend the following BOF sequence: 3C3F786D6C2076657273696F6E3D(22|27)312E30(22|27){20-256}3C736D696C

Sample of SMIL file with DOCTYPE can be found [here](https://archive.org/download/mac_Graphics_File_Formats_Second_Edition_1996/Graphics_File_Formats_Second_Edition_1996_daisy.zip).

@leninoc

**Comment by tnafrancesca** [comment]
I've updated the signature for the next release and credited both Archives New Zealand and Brigham Young University. Let me know if that isn't correct. Thank you for the submission
