### ISSUE TITLE
fmt/1568 signature is too broad and creates false-positives

### ISSUE THREAD

**Issue by luis100** [digital-preservation/PRONOM_Research#9]
In December 2021, the [fmt/1568](https://www.nationalarchives.gov.uk/PRONOM/fmt/1568) format was added to the registry, referring to the ISDOCX file format. This format has a very short signature (EOF; Offset:12-400; Magic bytes: 'isdoc') and normal priority which creates a lot of false-positives in our collections.

For example, an HTML file that has the "isdoc" string in the last 400 bytes is detected as this format, while it should be detected as an HTML.

![unnamed](https://user-images.githubusercontent.com/631728/167144058-6613dae3-8c8a-4d41-ab6d-a81deb8ce333.png)

Currently, the format is defined with the following priority settings:

- Has lower priority than ISDOCX Information System Document (6.0.1)
- Has priority over ZIP Format
- Has priority over ISDOC Information System Document (Generic) (5.x)
- Is supertype of ISDOC Information System Document (Generic) (5.x)

We are not familiar with the ISDOCX format, but, would it be possible to set it as a lower priority to the HTML family of formats?
Also, we noticed that  fmt/1567 (ISDOC 5.x) is a subtype of fmt/1568 (ISDOCX 5.x) and that this sub-format has a more precise signature, could it be that the signatures for these set of formats are not well defined and that the signature of the supertype could be redacted?

**Comment by AndreaHri** [comment]
Hello Luis, 

Thank you for alerting us to this clash. We had a look at the signature and updated fmt/1568 to include bytes associated with ZIP file format. This will be included in our next release (v105) which will be available to the public sometime this or next month.  We like to credit our contributors. I see in our previous releases your institution has been credited as KEEP SOLUTIONS. Would you like us to credit KEEP SOLUTIONS or you as an individual on this occasion? 

Best regards,
Andrea

**Comment by luis100** [comment]
Hi, please credit KEEP SOLUTIONS. Thank you for your amazing service!
